---
- hosts: all
  become: true
  vars:
    ansible_become_pass: "jenmar0112"
  tasks:
    - name: Ensure dpkg is configured (Ubuntu)
      raw: sudo dpkg --configure -a
      ignore_errors: yes
      changed_when: false

    - name: install update and repositories (Ubuntu)
      tags: always
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400
      changed_when: false

- hosts: controlnode
  become: true
  vars:
    ansible_become_pass: "jenmar0112"
  roles:
#    - role: create_FwRule
    - role: delete_FwRule
